name: billipod
description: "Bill Management with Secure and Private Solid Pod Storage"
publish_to: 'none'
version: 0.2.3+3

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  emacs_text_field: ^0.1.0
  gap: ^3.0.1
  file_picker: ^11.0.2
  intl: ^0.20.2
  markdown_tooltip: ^0.0.10
  open_filex: ^4.7.0
  pdf: ^3.11.1
  printing: ^5.13.1
  provider: ^6.1.5
  solidpod: ^0.12.9
  solidui: ^0.3.55
  uuid: ^4.5.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/app_image.jpg
