/// AppProvider — state management for BillPod.
///
// Time-stamp: <2026-04-14>
///
/// Copyright (C) 2026, Togaware Pty Ltd
///
/// Licensed under the GNU General Public License, Version 3

library;

import 'package:flutter/foundation.dart';

import 'package:billpod/constants/app.dart';
import 'package:billpod/models/bill.dart';
import 'package:billpod/services/pod_service.dart';

class AppProvider extends ChangeNotifier {
  List<Bill> _bills = [];
  bool _loading = false;
  String? _error;

  bool get loading => _loading;
  String? get error => _error;

  /// All bills sorted by due date (nulls last).
  List<Bill> get allBills => List.unmodifiable(_bills);

  List<Bill> get futureBills => _sorted(
    _bills.where((b) => b.status == BillStatus.future && !b.isTemplate).toList(),
  );

  List<Bill> get scheduledBills => _sorted(
    _bills.where((b) => b.status == BillStatus.scheduled).toList(),
  );

  List<Bill> get pastBills => _sortedDesc(
    _bills.where((b) => b.status == BillStatus.past).toList(),
  );

  List<Bill> get templateBills =>
      _bills.where((b) => b.isTemplate).toList();

  // ── Load / Save ────────────────────────────────────────────────────────────

  Future<void> loadFromPod() async {
    _loading = true;
    _error = null;
    notifyListeners();
    final loaded = await PodService.loadBills(billsFileName);
    if (loaded == null) {
      _error = 'Could not load bills from Pod.';
    } else {
      _bills = loaded;
      _expandRecurring();
    }
    _loading = false;
    notifyListeners();
  }

  Future<String?> saveToPod() async {
    final err = await PodService.saveBills(billsFileName, _bills);
    if (err != null) {
      _error = err;
      notifyListeners();
    }
    return err;
  }

  // ── CRUD ───────────────────────────────────────────────────────────────────

  void addBill(Bill bill) {
    _bills = [bill, ..._bills];
    if (bill.isTemplate) _expandRecurring();
    notifyListeners();
  }

  void updateBill(Bill bill) {
    _bills = [for (final b in _bills) b.id == bill.id ? bill : b];
    if (bill.isTemplate) _expandRecurring();
    notifyListeners();
  }

  void deleteBill(String id) {
    final bill = _bills.firstWhere((b) => b.id == id);
    // If deleting a template, also remove its expanded instances.
    if (bill.isTemplate) {
      _bills = _bills.where((b) => b.id != id && b.parentId != id).toList();
    } else {
      _bills = _bills.where((b) => b.id != id).toList();
    }
    notifyListeners();
  }

  /// Move a bill to a new status.
  void moveToStatus(String id, BillStatus newStatus) {
    _bills = [
      for (final b in _bills)
        if (b.id == id) b.copyWith(status: newStatus) else b,
    ];
    notifyListeners();
  }

  // ── Recurring expansion ────────────────────────────────────────────────────

  /// Expand recurring bill templates into individual Future instances for
  /// the next [expansionMonths] months, removing stale expansions first.
  void _expandRecurring() {
    final templates = _bills.where((b) => b.isTemplate).toList();
    // Remove existing auto-generated instances.
    _bills = _bills.where((b) => b.parentId == null || !_isAutoGenerated(b)).toList();

    final cutoff = DateTime.now().add(const Duration(days: expansionMonths * 31));
    final now = DateTime.now();

    for (final tmpl in templates) {
      if (tmpl.frequency == BillFrequency.oneOff) continue;
      if (tmpl.dueDate == null) continue;

      var next = tmpl.dueDate!;
      // Advance to the first future occurrence.
      while (next.isBefore(now)) {
        final n = tmpl.nextDueDate(next);
        if (n == null) break;
        next = n;
      }

      // Expand up to the cutoff.
      while (next.isBefore(cutoff)) {
        // Only add if no manual entry already exists for this date+parent.
        final alreadyExists = _bills.any(
          (b) =>
              b.parentId == tmpl.id &&
              b.dueDate != null &&
              _sameDay(b.dueDate!, next),
        );
        if (!alreadyExists) {
          _bills.add(Bill(
            title: tmpl.title,
            amount: tmpl.amount,
            dueDate: next,
            frequency: tmpl.frequency,
            status: BillStatus.future,
            paymentMethod: tmpl.paymentMethod,
            notificationMethod: tmpl.notificationMethod,
            parentId: tmpl.id,
            isTemplate: false,
          ));
        }
        final n = tmpl.nextDueDate(next);
        if (n == null) break;
        next = n;
      }
    }
  }

  /// Auto-generated instances have a parentId AND status == future.
  /// (Manual entries derived from a template also have parentId but have been
  /// individually edited — we never auto-delete those.)
  bool _isAutoGenerated(Bill b) =>
      b.parentId != null &&
      b.status == BillStatus.future &&
      b.notifiedDate == null &&
      b.scheduledDate == null &&
      b.note == null;

  bool _sameDay(DateTime a, DateTime b) =>
      a.year == b.year && a.month == b.month && a.day == b.day;

  List<Bill> _sorted(List<Bill> bills) {
    final copy = List<Bill>.from(bills);
    copy.sort((a, b) {
      if (a.dueDate == null && b.dueDate == null) return 0;
      if (a.dueDate == null) return 1;
      if (b.dueDate == null) return -1;
      return a.dueDate!.compareTo(b.dueDate!);
    });
    return copy;
  }

  List<Bill> _sortedDesc(List<Bill> bills) {
    final copy = List<Bill>.from(bills);
    copy.sort((a, b) {
      if (a.dueDate == null && b.dueDate == null) return 0;
      if (a.dueDate == null) return 1;
      if (b.dueDate == null) return -1;
      return b.dueDate!.compareTo(a.dueDate!);
    });
    return copy;
  }
}
